const projList = [
  {
    id: 0,
    name: "Pixi (Third Group Project)",
    description:
      "Project Three. E-commerse shop where users can buy and sell digital photography.",
    gitlink: "https://github.com/ajlaursen/Pixi",
    livesite: "https://pixi.pics.com/",
    technologies: [
      "MongoDB",
      "JWT",
      "Express",
      "AWS",
      "React",
      "Dotenv",
      "Axios",
      "Bcript",
      "Cors",
      "Mongoose",
      "TailwindCSS",
      "Passport",
      "HTML",
      "CSS",
      "JavaScript",
    ],
    image: "/pixi1.png",
  },
  {
    id: 1,
    name: "Character Sheet Generator (Second Group Project)",
    description:
      "Project two. Save character sheets in a database and access them anywhere with internet. Signup and login.",
    gitlink: "https://github.com/jasmineteters/Character-Sheet-Generator",
    livesite: "https://charactersheet-generator.herokuapp.com/",
    technologies: [
      "MySQL",
      "Sequelize",
      "Express",
      "Bcript",
      "Handlebars",
      "Dotenv",
      "TailwindCSS",
      "HTML",
      "CSS",
      "JavaScript",
    ],
    image: "/CSG.jpg",
  },
  {
    id: 2,
    name: "Parker's Googlebooks!",
    description:
      "Full Stack app to search books from the googlebooks api and save them to a public mongo server",
    gitlink: "https://github.com/MorgansPlayGames/parkers-googlebooks",
    livesite: "https://parkers-googlebooks.herokuapp.com/",
    technologies: [
      "HTML",
      "CSS",
      "React",
      "Bootstrap",
      "JavaScript",
      "MongoDB",
      "Node",
      "Axios",
    ],
    image: "/googlebooksearch.png",
  },
  {
    id: 3,
    name: "Parker's Quiz",
    description: "Quiz with a timer and local host high score page",
    gitlink: "https://github.com/MorgansPlayGames/parkers-quiz",
    livesite: "https://morgansplaygames.github.io/parkers-quiz/index.html",
    technologies: ["Bootstrap", "HTML", "CSS", "JavaScript"],
    image: "/QuizGame.png",
  },
  {
    id: 4,
    name: "Valence (first project)",
    description: "Search by tag music API",
    gitlink: "https://github.com/MorgansPlayGames/music-by-theme",
    livesite: "https://morgansplaygames.github.io/music-by-theme/",
    technologies: ["HTML", "CSS", "JavaScript", "JQuery", "Bootstrap", "AJAX"],
    image: "/Valence.jpg",
  },
];

export default projList;
